cpp17 = Environment(
	CCFLAGS=['-std=c++17', '-Wall', '-O0', '-g'])

cpp17.Program('class_template_argument_deduction.cpp')
cpp17.Program('structured_bindings.cpp')
cpp17.Program('open_nested_namespaces.cpp')
cpp17.Program('filesystem_path.cpp')
