cpp17 = Environment(
	CCFLAGS=['-std=c++17', '-Wall', '-O0', '-g'])

cpp17.Program('class_template_argument_deduction.cpp')
cpp17.Program('structured_bindings.cpp')
cpp17.Program('open_nested_namespaces.cpp')
cpp17.Program('filesystem_path.cpp')
cpp17.Program('string_view_basic.cpp')
#cpp17.Program('aligned_allocation.cpp')
cpp17.Program('inline_member_variable.cpp')
cpp17.Program('extract_node.cpp')
