env = Environment(
	CXXFLAGS=['-std=c++14', '-Wall', '-g', '-O0'])

env.ParseConfig('pkg-config --cflags --libs python2')

env.Program('simple.cpp')
env.Program('simple_from_file.cpp')
env.Program('extend.cpp')
env.Program('call_function.cpp')
env.Program('call_function_with_args.cpp')
env.Program('multiple_call_function.cpp')
