cpp17 = Environment(
	CPPFLAGS=['-std=c++17', '-g', '-O0', '-Wall'], LIBS=['pthread']
)

# C++11 environament

cpp11 = Environment(
	CPPFLAGS=['-std=c++11', '-g', '-O0', '-Wall'], LIBS=['pthread'])

cpp11.ParseConfig('pkg-config --cflags --libs libzmq')


# dependencies libzmq3, libczmq
#env.ParseConfig('pkg-config --cflags --libs libzmq libczmq')

#objs = env.Object(['kvsimple.c'])

# clone pattern
#env.Program(['clonesrv1.cpp', objs])
#env.Program(['clonecli1.cpp', objs])
#env.Program(['clonesrv2.cpp', objs])
#env.Program(['clonecli2.cpp', objs])
#env.Program(['clonesrv3.cpp', objs])
#env.Program(['clonecli3.cpp', objs])

# zmqpp pure c++ samples
#env.Program(['zmqpp/hwserver.cpp', objs])
#env.Program(['zmqpp/hwclient.cpp', objs])

# pure zmq
zmq_env = cpp17.Clone()
zmq_env.ParseConfig('pkg-config --cflags --libs libzmq')

zmq_env.Program('router_dealer_client.cpp')
zmq_env.Program('router_dealer_server.cpp')
#zmq_env.Program('router_dealer_server_msg.cpp')
#zmq_env.Program('router_dealer_server_pp.cpp')
#zmq_env.Program('mtserver.cpp')
zmq_env.Program('mtclient.cpp')
zmq_env.Program('rrserv_mon.cpp')
zmq_env.Program('publisher_subscriber.cpp')
zmq_env.Program('sighandling.cpp')
zmq_env.Program('sighandling_mt.cpp')
zmq_env.Program('publisher.cpp')
zmq_env.Program('subscriber.cpp')
zmq_env.Program('subscriber_mon.cpp')
zmq_env.Program('publisher_mon.cpp')
zmq_env.Program('dealer_mon.cpp')
zmq_env.Program('router_mon.cpp')
zmq_env.Program('pull_mon.cpp')
zmq_env.Program('push_mon.cpp')


cpp11.Program('router_legacy.cpp')
cpp11.Program('dealer_legacy.cpp')
cpp11.Program('pull_legacy.cpp')
cpp11.Program('push_legacy.cpp')



# cppzmq (zmq.hpp)
#env.Program('cppzmq/rrserv.cpp')
#env.Program('cppzmq/rrclient.cpp')
#env.Program('cppzmq/rrserv_mon.cpp')
