env = Environment(CPPFLAGS=['-std=c++11'])

# dependencies libzmq3, libczmq
env.ParseConfig('pkg-config --cflags --libs libzmq libczmq')

objs = env.Object(['kvsimple.c'])

# clone pattern
env.Program(['clonesrv1.cpp', objs])
env.Program(['clonecli1.cpp', objs])
env.Program(['clonesrv2.cpp', objs])
env.Program(['clonecli2.cpp', objs])
env.Program(['clonesrv3.cpp', objs])
env.Program(['clonecli3.cpp', objs])


# zmqpp pure c++ samples
env.Program(['zmqpp/hwserver.cpp', objs])
env.Program(['zmqpp/hwclient.cpp', objs])


# pure zmq
env.Program('router_dealer_client.cpp')
env.Program('router_dealer_server.cpp')
env.Program('router_dealer_server_msg.cpp')
