env = Environment()

# dependencies libzmq3, libczmq
env.ParseConfig('pkg-config --cflags --libs libzmq libczmq')

objs = env.Object(['kvsimple.c'])

# clone pattern
env.Program(['clonesrv1.cpp', objs])
env.Program(['clonecli1.cpp', objs])
env.Program(['clonesrv2.cpp', objs])
env.Program(['clonecli2.cpp', objs])
