env = Environment(
	CXXFLAGS = ['-std=c++14', '-g', '-Wall', '-O0'],
	LIBS = ['pthread', 'boost_system', 'boost_regex']
)

env.ParseConfig('pkg-config --cflags --libs libzmq')

env.Program('hello.cpp')
env.Program('spawn.cpp')
env.Program('pair_pair.cpp')
