env = Environment(
	CXXFLAGS = ['-std=c++17', '-Wall', '-g', '-O0'],
	LIBS = ['pthread', 'boost_system', 'boost_regex']
)

env.ParseConfig('pkg-config --cflags --libs libzmq')

env.Program('hello.cpp')
#env.Program('spawn.cpp')
env.Program('pair_pair.cpp')
env.Program('router_dealer_async_thread.cpp')
env.Program('publisher_subscriber.cpp')
env.Program('router_dealer.cpp')
env.Program('buffer.cpp')
env.Program('pull_push.cpp')
