env = Environment(
	CXXFLAGS=['-std=c++14', '-Wall', '-O0', '-g'])

env.ParseConfig('pkg-config --cflags --libs xcb')

env.Program('hello.cpp')
env.Program('basics.cpp')
env.Program('no_decoration.cpp')
env.Program('move.cpp')
env.Program('unmap.cpp')
