env = Environment(
	CCFLAGS=['-std=c++11'],
	LIBS=['pthread']
)

#env.Program('condition_var.cpp') 
env.Program('thread_use.cpp') 
env.Program('terminate.cpp') 
env.Program('atomic_counter.cpp') 
env.Program('lock_in_loop.cpp') 
env.Program('thread_joinable.cpp')
