# dependencies: libglib2.0-dev

cpp17 = Environment(CCFLAGS=['-O0', '-g', '-Wall'],
	CXXFLAGS=['-std=c++17'])

cpp17.ParseConfig('pkg-config --cflags --libs glib-2.0')

cpp17.Program('cmdparse.cpp')
cpp17.Program('venc.cpp')
