env = Environment(
	CPPFLAGS=['-std=c++11'],
	CCFLAGS=['-Wall'],
	LIBS=['gtest', 'gtest_main', 'pthread']
)

import os  # pridaj farbu ak pouzivam clang
if 'TERM' in os.environ:
	env['ENV']['TERM'] = os.environ['TERM']

env.Program('test_forward_list.cpp')
env.Program('touches.cpp')
