env = Environment(
	CCFLAGS=['-std=c++11', '-Wall', '-O0', '-g']
)

env.ParseConfig('pkg-config --cflags --libs libvlc sdl2')

env.Program('simple_play.cpp')
env.Program('sdl_render.cpp')
env.Program('vlc_abstr.cpp')
