env = Environment(
	CCFLAGS=['-std=c++11', '-Wall', '-O0', '-g']
)

env.ParseConfig('pkg-config --cflags --libs libvlc sdl2')

objs = env.Object(['vlc_player.cpp'])

env.Program('simple_play.cpp')
env.Program('sdl_render.cpp')
env.Program('vlc_abstr.cpp')
env.Program('events.cpp')
env.Program('track_info.cpp')
env.Program(['test_player.cpp', objs])
