env = Environment(
	CCFLAGS=['-std=c++11', '-Wall', '-O0', '-g'],
	LIBS=['pthread']
)

env.ParseConfig('pkg-config --cflags --libs libvlc sdl2')

objs = env.Object([
	'vlc_player.cpp',
	'sdl2_player.cpp'
])

env.Program('simple_play.cpp')
env.Program('sdl_render.cpp')
env.Program('vlc_abstr.cpp')
#env.Program('events.cpp')
env.Program('track_info.cpp')
env.Program(['test_player.cpp', objs])
env.Program(['stream_server.cpp'])
env.Program(['simple_stream_serv_abstr.cpp'])
env.Program(['stream_client.cpp'])
env.Program(['stream_server_thread.cpp'])
env.Program(['playlist_player.cpp'])
env.Program(['playlist_player_stop.cpp'])
