# dependencies: libgstreamer1.0-dev libgstrtspserver-1.0-dev
env = Environment(
	CXXFLAGS=['-std=c++17', '-Wall', '-g', '-O0'])

env.ParseConfig('pkg-config --cflags --libs gstreamer-1.0 gstreamer-pbutils-1.0 gstreamer-video-1.0 gstreamer-rtsp-server-1.0 gtk+-3.0')

env.Program('initialization.cpp')
env.Program('test-readme.c')
env.Program('test-mp4.c')
env.Program('test-multicast.c')
env.Program('test-multicast2.c')

# basic tutorial
env.Program('basic_01.cpp')
env.Program('basic_02.cpp')
env.Program('basic_03.cpp')
env.Program('basic_04.cpp')
env.Program('basic_05.cpp')  # simple GTK GUI
env.Program('basic_09.cpp')  # media discover

# playing tutorial

# tests
env.Program('play.cpp')
env.Program('thread_safe_player.cpp')
env.Program('play_rtsp.cpp')

env.Program('video_parse.cpp')
env.Program('video_capi.cpp')
env.Program('audio_capi.cpp')
env.Program('video_enc.cpp')
