env = Environment(
	CXX = 'clang++',
	CXXFLAGS=['-std=c++11'],
	CCFLAGS=['-Wall'],
	LIBS=['boost_filesystem', 'boost_system']
)

env.Program('hello.cpp')
env.Program('compare.cpp')
env.Program('relative.cpp')
env.Program('path_iter.cpp')
#env.Program('playground.cpp')
env.Program('path_test.cpp')
env.Program('directory_listing.cpp')
env.Program('relative_func.cpp')
env.Program('sub_path.cpp')
