import os

env = Environment(
	CXXFLAGS=['-std=c++14', '-g', '-O0', '-Wall'],
	LIBS=[],
	CXX='clang++')

if 'ENV' in env and 'TERM' in env['ENV']:  # enable colors for clang output
	env['ENV']['TERM'] = os.environ['TERM']

env.Program(['dfs_example.cpp'])
env.Program(['topo_sort_file_dep.cpp'])
env.Program(['cycle_file_dep.cpp'])
env.Program(['topo_sort_file_dep2.cpp'])
env.Program(['cycle_file_dep2.cpp'])
env.Program(['accum_compile_times.cpp'])
env.Program(['parallel_compile_time.cpp'])
env.Program(['dfs_hello.cpp'])
env.Program(['graph_types.cpp'])
env.Program(['property_as_vector.cpp'])
env.Program(['property_as_map.cpp'])
env.Program(['colormap.cpp'])
env.Program(['list_vec_graph.cpp'])
env.Program(['topological_sort.cpp'])
env.Program(['vector_as_graph.cpp'])
