import os

env = Environment(
	CXXFLAGS=['-std=c++14'],
	CFLAGS=['-Wall', '-g', '-O0'],
	LIBS=[],
	CXX='clang++')

env['ENV']['TERM'] = os.environ['TERM']  # enable colors in clang output

env.Program(['dfs_example.cpp'])
env.Program(['topo_sort_file_dep.cpp'])
env.Program(['cycle_file_dep.cpp'])
env.Program(['topo_sort_file_dep2.cpp'])
env.Program(['cycle_file_dep2.cpp'])
env.Program(['accum_compile_times.cpp'])
env.Program(['parallel_compile_time.cpp'])
env.Program(['dfs_hello.cpp'])
env.Program(['graph_types.cpp'])
env.Program(['property_as_vector.cpp'])
env.Program(['property_as_map.cpp'])
env.Program(['colormap.cpp'])
