# SConstruct: use scons --build-release in case optimized binery required

AddOption('--build-release', action='store_true', dest='build_release', 
	help='generate optimized binary', default=False)

build_path = 'build-debug'
if GetOption('build_release'):
	build_path = 'build-release'

VariantDir(build_path, 'source', duplicate=0)

env = Environment(CCFLAGS=['-Wall'])

# apply debug/release options
if not GetOption('build_release'):
	env.Append(CCFLAGS=['-ggdb3', '-Og', '-DDEBUG'])
else: # --build-release
	env.Append(CCFLAGS=['-Os', '-DNDEBUG'])

env.Program('%s/%s' % (build_path, 'main.cpp'))
