env = Environment(
	CC='clang',
	CXX='clang++',
	CXXFLAGS=['-std=c++14', '-Wall'], 
	LIBS=[
		'boost_filesystem', 
		'boost_system', 
		'boost_thread',
		'boost_chrono',
		'pthread'
	]
)

env.Program('daytime1.cpp')
env.Program('tcp_sync_echo_client.cpp')
env.Program('tcp_sync_echo_server.cpp')
env.Program('deadline_timer.cpp')
env.Program('simple_timer.cpp')
env.Program('singlethread_events.cpp')
env.Program('multithread_events.cpp')
env.Program('steady_timer.cpp')
env.Program('multithread_steady_timer.cpp')
env.Program('forever_steady_timer.cpp')
env.Program('endless_run.cpp')
env.Program('work.cpp')
