ccflags = ['-O0', '-ggdb3', '-Wall', '-Wextra']
libs = ['pthread']

cpp20 = Environment(
	#CC='clang',
	#CXX='clang++',
	CXXFLAGS=['-std=c++20', '-Wall', '-O0', '-g'], 
	LIBS=[
		'boost_filesystem', 
		'boost_system', 
		'boost_thread',
		'boost_chrono',
		'pthread'
	]
)

cpp17_d10 = Environment(  # Debian 10 cpp invironment (on not Debian 10 systems we expect boost to be installed in /usr/local).
	CXXFLAGS=['-std=c++17'],
	CCFLAGS=ccflags,
	CPPDEFINES='',
	LIBS=libs + ['boost_system'],
	LIBPATH=['/usr/local/lib'])

cpp17_d10.ParseConfig('pkg-config --cflags --libs openssl')


cpp20.Program('daytime1.cpp')
cpp20.Program('tcp_sync_echo_client.cpp')
cpp20.Program('tcp_sync_echo_server.cpp')
cpp20.Program('deadline_timer.cpp')
cpp20.Program('simple_timer.cpp')
cpp20.Program('singlethread_events.cpp')
cpp20.Program('multithread_events.cpp')
cpp20.Program('steady_timer.cpp')
cpp20.Program('endless_run.cpp')
cpp20.Program('work.cpp')
cpp20.Program('work_remove.cpp')
cpp20.Program('service_poll.cpp')
cpp20.Program('post.cpp')
cpp20.Program('shutdown.cpp')
cpp20.Program('interrupt_handling.cpp')
cpp20.Program('athread.cpp')
cpp20.Program('post_with_result.cpp')
cpp20.Program('asio_loop.cpp')
cpp20.Program('async_loop.cpp')
cpp20.Program('async_file.cpp')
cpp20.Program('socket_async_connect.cpp')
cpp20.Program('socket_async_connect_resolver.cpp')

# Debian 10 boost samples
cpp17_d10.Program('ssl_client_d10.cpp')
cpp17_d10.Program('ssl_server_d10.cpp')
