sdl_env = Environment(CXXFLAGS=['-std=c++17'])
sdl_env.ParseConfig('pkg-config --cflags --libs sdl2')

sdl_env.Program(['hello.cpp'])
sdl_env.Program(['hello_poll.cpp'])
sdl_env.Program(['error_processing.cpp'])


mixer_env = Environment(CXXFLAGS=['-std=c++17'])
mixer_env.ParseConfig('pkg-config --cflags --libs sdl2 SDL2_mixer')

mixer_env.Program(['audio.cpp'])
mixer_env.Program(['mixer.cpp'])


# for OpenGL samples
ogl_env = Environment(CXXFLAGS=['-std=c++17'])
ogl_env.ParseConfig('pkg-config --cflags --libs sdl2 glesv2 glm')

ogl_env.Program(['ogles32.cpp'])
ogl_env.Program(['triangle.cpp'])
ogl_env.Program(['axis.cpp'])

