sdl_env = Environment(CXXFLAGS=['-std=c++17'])
sdl_env.ParseConfig('pkg-config --cflags --libs sdl2')

sdl_env.Program(['hello.cpp'])
sdl_env.Program(['hello_poll.cpp'])
sdl_env.Program(['error_processing.cpp'])


mixer_env = Environment(CXXFLAGS=['-std=c++17'])
mixer_env.ParseConfig('pkg-config --cflags --libs sdl2 SDL2_mixer')

mixer_env.Program(['audio.cpp'])
mixer_env.Program(['mixer.cpp'])
