env = Environment(
	CCFLAGS=['-std=c++14', '-O0', '-g', '-Wall'],
	CPPPATH=['agg-2.5/include']
)

# build library with x11 support

env.ParseConfig('pkg-config --cflags --libs x11')

agg_lib = env.StaticLibrary('agg', [
	Glob('agg-2.5/src/*.cpp'),
	Glob('agg-2.5/src/ctrl/*.cpp'),
	Glob('agg-2.5/src/platform/X11/*.cpp')
])

# examples
env.Program(['agg-2.5/examples/line_patterns.cpp', agg_lib])


# my samples
env.Program(['t01_rendering_buffer.cpp', agg_lib])
env.Program(['t02_pixel_formats.cpp', agg_lib])
env.Program(['t03_solar_spectrum.cpp', agg_lib])
env.Program(['t04_alpha_mask.cpp', agg_lib])
env.Program(['line_patterns.cpp', agg_lib])
