# dependency:
#	libjpeg-turbo8-dev (ubuntu 15.10, 1.3.0)
#  libmagick++-dev (ubuntu 15.10, 6.8.9.9)

env = Environment(
	CXXFLAGS = ['-std=c++11', '-O0', '-g', '-Wall'],
	LIBS=['jpeg'])

env.ParseConfig('pkg-config --cflags --libs Magick++')

env.Program('read.cpp')
env.Program('write.cpp')
env.Program('header_info.cpp')
env.Program('rawread.cpp')
