# at least gcc10 with -std=c++20 -fcoroutines
cpp20 = Environment(
	CXX='g++-10',
	CCFLAGS=['-std=c++20', '-fcoroutines'],
	LIBS=['pthread'])

cpp20.Program('infinite_data_stream.cpp')
cpp20.Program('condition_variables.cpp')
cpp20.Program('sender_receiver.cpp')
#cpp17.Program('task.cpp')
