gcc = Environment(CCFLAGS=['-Wall', '-g'])

clang = Environment(CXX='clang++', 
	CCFLAGS=['-Wall', '-g'])

# in GCC address sanitizer includes also leak sanitizer
gcc_address = gcc.Clone(CCFLAGS=['-fsanitize=address'],
	LINKFLAGS=['-fsanitize=address'])

clang_memory = clang.Clone()
clang_memory.Append(CCFLAGS=['-fsanitize=memory'],
	LINKFLAGS=['-fsanitize=memory'])

gcc_address.Program('address.cpp')
clang_memory.Program('memory.cpp')

# catch2 is expected to be installed
catch = gcc_address.Clone()

catch.Program('samples.cpp')
