#!/bin/bash

COVERAGE_REPORT_PATH=coverage_report

mkdir -p ${COVERAGE_REPORT_PATH}

# run tests
./test

# generate machine readable XML reoprt
gcovr -r . --xml-pretty . -o ${COVERAGE_REPORT_PATH}/coverage.xml

# generate human readable HTML report
gcovr -r . --html-details -o ${COVERAGE_REPORT_PATH}/index.html

# clean up
find  . -depth -type f -name '*.gcda' -exec rm '{}' ';'
