env = Environment(
	CCFLAGS=['-Wall', '-g', '-O0'],
	CPPFLAGS=['-std=c++11'],
	LIBS=['glut'])

env.ParseConfig('pkg-config --libs --cflags glew')

env.Program('simple_window.cpp')
env.Program('window_layer.cpp')
