env = Environment(
	CPPFLAGS=['-std=c++11', '-g', '-O0'],
	LIBS=['pthread']
)

env.ParseConfig('pkg-config --cflags --libs libzmq')

# cppzmq (zmq.hpp)
env.Program('rrserv.cpp')
env.Program('rrclient.cpp')
env.Program('rrserv_mon.cpp')

env.Program('poller_and_probe.cpp')
