env = Environment(
	CCFLAGS=['-std=c++11', '-Wall', '-g', '-O0'],
	LIBS=['boost_python']
)

env.ParseConfig('pkg-config --libs --cflags python-2.7')

# expose
env.Program('hello.cpp')
env.Program('expose_struct.cpp')
env.Program('struct_with_ctors.cpp')
env.Program('expose_struct_data_memebers.cpp')

# TODO: how to name so files hello.so, not libhello.so ?
env.SharedLibrary('hello.so', ['hellomodule.cpp'])
