env = Environment(
	CCFLAGS=['-std=c++11', '-Wall', '-g', '-O0'],
	LIBS=['boost_python']
)

env.ParseConfig('pkg-config --libs --cflags python-2.7')

env.Program('hello.cpp')

env.SharedLibrary('hello.so', ['hellomodule.cpp'])
