cpp17 = Environment(
	CCFLAGS=['-Wall', '-g', '-O0'],
	CPPFLAGS=['-std=c++17'],
	LIBS=['glut'])

cpp17.ParseConfig('pkg-config --libs --cflags glew')

cpp17.Program('simple_window.cpp')
cpp17.Program('window_layer.cpp')
cpp17.Program('window_user_input.cpp')

# glut only
cpp17.Program('solid_objects.cpp')
