env = Environment(
	CPPFLAGS=['-std=c++11', '-g', '-O0', '-Wall'],
	LIBS=['pthread', 'gtest', 'png']
)

env.ParseConfig('pkg-config --cflags --libs Magick++')

env.Program('gradient.cpp')
env.Program('interleaved_view.cpp')
env.Program('rgba8_from_raw.cpp')
env.Program('gil_vs_imagick.cpp')
env.Program('image_from_file.cpp')
env.Program('subimage_view.cpp')
env.Program('pixels_from_image.cpp')
env.Program('flip_view.cpp')
env.Program('flipped_pixels.cpp')
#env.Program('runtime_image.cpp')
env.Program('read_as_rgba8.cpp')
