env = Environment(
	CCFLAGS=['-std=c++14', '-Wall', '-O0', '-g']
)

env.Program('quick_start.cpp')
env.Program('custom_point.cpp')
env.Program('expand.cpp')
env.Program('centroid_box.cpp')
env.Program('expand_box.cpp')
env.Program('distance_on_earth.cpp')
env.Program('point.cpp')
env.Program('polygon.cpp')
env.Program('ring.cpp')
env.Program('envelope.cpp')
