env = Environment(
	CXX='clang++', CXXFLAGS=['-std=c++14'], CCFLAGS=['-Wall', '-g', '-O0'])

cpp14 = env.Clone()
cpp17 = Environment(
	CXX='clang++', CXXFLAGS=['-std=c++17'], CCFLAGS=['-Wall', '-g', '-O0'])

catch17 = Environment(
	CXX='clang++',
	CXXFLAGS=['-std=c++17'], 
	CCFLAGS=['-Wall', '-g', '-O0'],
	CPPDEFINES=['CATCH_CONFIG_MAIN'])

import os  # enable color in output for clang
if 'TERM' in os.environ:
	env['ENV']['TERM'] = os.environ['TERM']

env.Program('set_container.cpp')
env.Program('set_container_sort.cpp')
env.Program('listener_function.cpp')
env.Program('listener_visitor.cpp')
env.Program('istream_iterator_file.cpp')
env.Program('path_tail.cpp')
env.Program('game_fsm.cpp')
env.Program('game_fsm2.cpp')
env.Program('game_fsm3.cpp')
env.Program('crtp.cpp')
env.Program('struct_hier.cpp')
env.Program('ref_to_ptr.cpp')
env.Program('value_proxy.cpp')
env.Program('getline.cpp')

cpp14.Program('filter.cpp')
cpp14.Program('filter_ptr.cpp')
cpp14.Program('pretty_function_macro.cpp')
cpp14.Program('file_name_from_file.cpp')
#cpp14.Program('derived_inner_class.cpp')
cpp14.Program('observer.cpp')
cpp14.Program('inheritance_from_base_ctor.cpp')

cpp14.Program('openfile.cpp')
cpp14.Program('float_and_literal_comparsion.cpp')

catch17.Program('equal.cpp')

cpp14.Program('avoid_hierarchy.cpp')
