# libglfw3-dev (3.2.1, ubuntu 18.04)

# gl
env = Environment()
env.ParseConfig('pkg-config --cflags --libs glfw3 gl glu')

env.Program('hello.cpp')

# gles2
gles2_env = Environment(
	CPPDEFINES=['GLFW_INCLUDE_ES2']
)
gles2_env.ParseConfig('pkg-config --cflags --libs glfw3 glesv2')

gles2_env.Program('triangle_gles2.cpp')
