env = Environment(
	CCFLAGS=['-std=c++14', '-Wall', '-g', '-O0'],
	LIBS=['boost_log', 'boost_system', 'boost_thread', 'pthread'],
	CPPDEFINES=['BOOST_LOG_DYN_LINK']
)

env.Program('trivial.cpp')
env.Program('trivial_filters.cpp')
env.Program('tofile.cpp')
env.Program('custom_backend_sink.cpp')
env.Program('console_log.cpp')
env.Program('constant_attribute.cpp')
env.Program('mutable_constant_attribute.cpp')
env.Program('error_code_attribute.cpp')
env.Program('error_code_attribute2.cpp')
#env.Program('custom_attribute.cpp')
env.Program('error_attrib.cpp')
env.Program('two_loggers.cpp')
env.Program('custom_logger.cpp')
