# requirements: libboost-log-dev (tested with 1.71 version)
ccflags = ['-Wall', '-Wextra', '-ggdb3', '-O0']
libs = ['boost_log', 'boost_log_setup', 'boost_system', 'boost_thread', 'pthread']
cppdefines = ['BOOST_LOG_DYN_LINK']

cpp14 = Environment(
	CXXFLAFS=['-std=c++14'],
	CCFLAGS=ccflags,
	LIBS=libs,
	CPPDEFINES=cppdefines)

cpp17 = Environment(
	CXXCFLAGS=['-std=c++17'],
	CCFLAGS=ccflags,
	LIBS=libs,
	CPPDEFINES=cppdefines)

cpp14.Program('trivial.cpp')
cpp14.Program('trivial_filters.cpp')
cpp14.Program('custom_backend_sink.cpp')
cpp14.Program('console_log.cpp')
cpp14.Program('constant_attribute.cpp')
cpp14.Program('mutable_constant_attribute.cpp')
cpp14.Program('error_code_attribute.cpp')
cpp14.Program('error_code_attribute2.cpp')
cpp14.Program('error_attrib.cpp')
cpp14.Program('two_loggers.cpp')
cpp14.Program('custom_logger.cpp')
cpp14.Program('line_id_attrib.cpp')
cpp14.Program('custom_feature.cpp')
cpp14.Program('custom_attribute.cpp')
cpp14.Program('custom_feature_mt.cpp')
cpp14.Program('extension_record_tagger.cpp')
cpp17.Program('tutorial_file.cpp')
cpp17.Program('tofile.cpp')
cpp17.Program('tofile_append.cpp')
cpp17.Program('tofile_rotate.cpp')
