env = Environment(
	CCFLAGS=['-std=c++14', '-Wall', '-g'])

env.Program(['hello.cpp'])
env.Program(['time_point.cpp'])
env.Program(['clock.cpp'])
env.Program(['chrono_now.cpp'])
env.Program('fract_duration.cpp')
env.Program('duration_diff.cpp')
