env = Environment(CXXFLAGS=['-std=c++14', '-Wall', '-g', '-O0'])

env.Program('priority_queue.cpp')
env.Program('move_map.cpp')
#env.Program('input_iterator.cpp')
env.Program('search_range.cpp')
env.Program('filtered_range.cpp')
