env = Environment(CCFLAGS=['-Wall', '-g', '-O0'])

cpp14 = env.Clone(CXXFLAGS=['-std=c++14'])

cpp20 = env.Clone(CXXFLAGS=['-std=c++20'])

cpp14.Program('priority_queue.cpp')
cpp14.Program('move_map.cpp')
#env.Program('input_iterator.cpp')
cpp14.Program('search_range.cpp')
cpp14.Program('filtered_range.cpp')

cpp20.Program('parallel_transform.cpp')
