env = Environment(
	CXXFLAGS=['-std=c++11', '-g', '-O0'], 
	LIBS=['pthread']
)

env.ParseConfig('pkg-config --cflags --libs libevent')

env.Program('hello_server.cpp')
env.Program('hello_multithread_server.cpp')
