env = Environment()
env['CXX'] = 'clang++'
env.Append(
	CXXFLAGS=['-std=c++11'],
	CCFLAGS=['-O0', '-Wall'],
	LIBS=['boost_filesystem', 'boost_system', 'boost_regex'])

env.Program('rename.cpp')
env.Program('tokenizer.cpp')
