env = Environment(
	CXXFLAGS=['-std=c++11', '-Wall', '-g'])

env.ParseConfig('pkg-config --cflags --libs gstreamer-1.0 gstreamer-rtsp-server-1.0')

env.Program('server_init.cpp')
env.Program('hello.cpp')
