env = Environment(
	CCFLAGS=['-std=c++17', '-Wall', '-g', '-O0']
)

env.ParseConfig('pkg-config --libs --cflags tbb')

env.Program('init.cpp')
env.Program('parallel_for.cpp')
env.Program('average.cpp')
env.Program('auto_partitioner.cpp')
env.Program('parallel_reduce.cpp')
env.Program('min_index.cpp')
