env = Environment(
	CPPFLAGS=['-std=c++14', '-Wall', '-g', '-O0']
)

env.ParseConfig('pkg-config gtkmm-3.0 --cflags --libs')

env.Program('base.cpp')
env.Program('17.2.1_myarea.cpp')
env.Program('17.2.3_thin_line.cpp')
env.Program('17.3.1_curved_lines.cpp')
env.Program('17.5.2_text.cpp')
env.Program('17.6.1_drawing_images.cpp')
env.Program('clock.cpp')
env.Program('23.1.1_keyboard_events.cpp')
env.Program('23.2.1_keyboard_events_propagation.cpp')
env.Program('combobox.cpp')
env.Program('fixed.cpp')

# my
env.Program('paint.cpp')
env.Program('point_representation.cpp')
