language: cpp
dist: trusty
addons:
  apt:
    packages:
    - cmake
    - libboost-filesystem-dev
    - libboost-test-dev
compiler:
- gcc
os:
- linux
script:
- export CXX=g++
- export CC=gcc
- export CODECOV_TOKEN="c3d08772-6107-422c-886f-ada5c4780d5c"
- mkdir build && cd build
- cmake --version
- g++ --version
- cat /usr/include/boost/version.hpp
- cmake .. -DINOTIFY_GCC_COVERAGE=1
- cmake --build .
- ctest -VV
- bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'

