env = Environment(
	CXX=['clang++'],
	CPPFLAGS=['-std=c++11', '-g', '-O0'], 
	CPPDEFINES=['GLM_FORCE_RADIANS'])

import os
if 'TERM' in os.environ:
	env['ENV']['TERM'] = os.environ['TERM']

env.Program('lookat.cpp')
env.Program('sample.cpp')
env.Program('projection.cpp')
env.Program('quatmat.cpp')
#env.Program('rotations.cpp')
#env.Program('matconcat.cpp')
env.Program('curlyconstruct.cpp')
env.Program('curlyb.cpp')
env.Program('ortho.cpp')
env.Program('projection_play.cpp')

# unable to compile with glm 0.9.9.0
#env.Program('vector_angle.cpp')

env.Program('test_adapt.cpp')
env.Program('vec2_adapt.cpp')
