env = Environment(
	CXXFLAGS=['-std=c++14', '-Wall', '-O0', '-g']
)

env.ParseConfig('net-snmp-config --cflags --libs --agent-libs')

env.Program('sync_app.cpp')
env.Program('send_trap.cpp')
env.Program('oidmanip.cpp')
env.Program('ask_pm.cpp')
env.Program('variable_traits.cpp')
env.Program('client.cpp')
env.Program('table.cpp')
