env = Environment(
	#CC='clang',
	#CXX='clang++',
	CXXFLAGS=['-std=c++14', '-Wall', '-O0', '-g']
)

env.ParseConfig('net-snmp-config --cflags --libs')

env.Program('sync_app.cpp')
env.Program('send_trap.cpp')
env.Program('oidmanip.cpp')
env.Program('ask_pm.cpp')
env.Program('variable_traits.cpp')
env.Program('client.cpp')
