env = Environment(
	CCFLAGS=['-std=c++11', '-Wall', '-g', '-O0']
)

env.Program('debug_settings.cpp')
env.Program('json_settings.cpp')
env.Program('json_from_string.cpp')
env.Program('json_forloop.cpp')
env.Program('json_named_array.cpp')
env.Program('json_ls.cpp')
env.Program('json_array_of_objects.cpp')
env.Program('bad_path.cpp')
env.Program('json_null.cpp')
