cpp11 = Environment(
	CCFLAGS=['-std=c++11', '-Wall', '-g', '-O0']
)

cpp11.Program('debug_settings.cpp')
cpp11.Program('json_settings.cpp')
cpp11.Program('json_from_string.cpp')
cpp11.Program('json_forloop.cpp')
cpp11.Program('json_ls.cpp')
cpp11.Program('json_array_of_objects.cpp')
cpp11.Program('bad_path.cpp')
cpp11.Program('json_null.cpp')
cpp11.Program('vector_put.cpp')
cpp11.Program('json_array.cpp')
cpp11.Program('json_keyval_and_array.cpp')
