ccflags = ['-O0', '-ggdb3', '-Wall', '-Wextra']
cppdefines = ['BOOST_BEAST_USE_STD_STRING_VIEW']
libs = ['pthread']

cpp17 = Environment(
	CXXFLAGS=['-std=c++17'],
	CCFLAGS=ccflags,
	CPPDEFINES=cppdefines,
	LIBS=libs)

cpp17.Program('ws_sync_client.cpp')

cpp20 = Environment(
	CXXFLAGS=['-std=c++2a'],
	CCFLAGS=ccflags,
	CPPDEFINES=cppdefines,
	LIBS=libs
)

cpp17_d10 = Environment(
	CXXFLAGS=['-std=c++17'],
	CCFLAGS=ccflags,
	CPPDEFINES='',
	LIBS=libs + ['boost_system'],
	LIBPATH=['/usr/local/lib'])

# Ubuntu 20.04 LTS (boost 1.71) samples
cpp17.Program('http_client_async.cpp')
cpp17.Program('http_get.cpp')
cpp20.Program('http_get_future.cpp')
cpp20.Program('http_server_small.cpp')
cpp20.Program('http_server_async.cpp')
cpp20.Program('http_responder.cpp')

# Debian 10 (boost 1.67) samples
cpp17_d10.Program('http_get_d10.cpp')
