cpp = Environment(
	CCFLAGS=['-g', '-O0', '-Wall'],
	LINKFLAGS=['-rdynamic'],
	LIBS=['pthread', 'dl']
)

cpp11 = cpp.Clone()
cpp11.Append(CCFLAGS=['-std=c++11'])

cpp17 = cpp.Clone()
cpp17.Append(CCFLAGS=['-std=c++17'])

cpp.Program('ls.cpp')
cpp.Program('dirit.cpp')
cpp.Program('reentrant_ls.cpp')
cpp.Program('sighandler_signal.cpp')
cpp.Program('sighandler_sigaction.cpp')
cpp.Program('backtrace.cpp')
cpp.Program('stack_trace_on_sigsegv.cpp')
cpp.Program('backtrace_with_signals.cpp')
cpp.Program('demangled_backtrace.cpp')
cpp.Program('hostname.cpp')
cpp.Program('demangling.cpp')
cpp.Program('readlink.cpp')
cpp.Program('unwind.cpp')
cpp.Program('ip_address.cpp')
cpp.Program('select.cpp')

cpp11.Program('ioctl_iflags.cpp')
cpp11.Program('multicast_send.cpp')

cpp17.Program('sigint_handler.cpp')
cpp17.Program('count_fds.cpp')
cpp17.Program('count_fds2.cpp')
cpp17.Program('lot_of_fds.cpp')
