env = Environment(
	#CXX='clang++',
	CCFLAGS=['-g', '-O0', '-rdynamic'],
	CPPFLAGS=['-std=c++11'])

env.Program('ls.cpp')
env.Program('dirit.cpp')
env.Program('reentrant_ls.cpp')
env.Program('sighandler.cpp')
env.Program('backtrace.cpp')
env.Program('hostname.cpp')
