env = Environment(
	CCFLAGS=['-std=c++11', '-g', '-O0'],
	LINKFLAGS=['-rdynamic'],
	LIBS=['pthread']
)

env.Program('ls.cpp')
env.Program('dirit.cpp')
env.Program('reentrant_ls.cpp')
env.Program('sighandler_signal.cpp')
env.Program('sighandler_sigaction.cpp')
env.Program('backtrace.cpp')
env.Program('stack_trace_on_sigsegv.cpp')
env.Program('backtrace_with_signals.cpp')
env.Program('demangled_backtrace.cpp')
env.Program('hostname.cpp')
env.Program('sigint_in_multithread_app.cpp')
env.Program('demangling.cpp')
