env = Environment(
	CCFLAGS=['-std=c++11', '-Wall', '-g', '-O0'],
	LIBS=['boost_date_time']
)

env.Program('date.cpp')
env.Program('getting_date.cpp')
env.Program('duration.cpp')
env.Program('posix_time_time_period.cpp')
env.Program('posix_time.cpp')
env.Program('custom_date_format.cpp')
env.Program('time_input_facet.cpp')
env.Program('date_comparison.cpp')
env.Program('parse_custom_date.cpp')
env.Program('local_to_utc.cpp')
env.Program('posix_time2.cpp')
env.Program('ptime_string_conv.cpp')
env.Program('local_time.cpp')
env.Program('utc_now.cpp')
