# generate program using share library
prog_env = Environment(
	CPPFLAGS=['-std=c++11'],
	LIBS=['staticfoo'],
	LIBPATH=['.'],
	LINKFLAGS=['-Wl,-rpath,.']
)

prog_env.Program('hellostatic', ['main.cpp'])
