env = Environment(
	CXXFLAGS=['-std=c++11', '-O0', '-g', '-Wall']
)

env.ParseConfig(
	'pkg-config --cflags --libs libavformat-ffmpeg libavutil-ffmpeg libavcodec-ffmpeg')

env.Program('metadata.cpp')
env.Program('video_geometry.cpp')
