# generate shared library
lib_env = Environment(CPPFLAGS=['-std=c++11'])
lib_env.SharedLibrary('foo.cpp')

# generate program using share library
prog_env = Environment(
	CPPFLAGS=['-std=c++11'],
	LIBS=['foo'],
	LIBPATH=['.'],
	LINKFLAGS=['-Wl,-rpath,.']
)

prog_env.Program('helloshared', ['main.cpp'])
